### ISSUE TITLE
Use of YAML for properties

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#1]
PP Pending - Phase2

Use of application.yml instead of application.properties (take care of profiles too)

YAML Reference:
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-use-yaml-for-external-properties

For multiple profiles:
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-multi-profile-yaml

does it worth the time?

**Comment by imarban** [comment]
I'd prefer YAML files over properties because it looks more organized, legible and maintainable. But I think we could need to load them via PropertySource and we'll face many problems with that. Avoid them until Spring add support for that.

**Comment by wdonet** [comment]
Marked as won't do since we did not find any advantage over using properties
