### ISSUE TITLE
Improve the url mapping in views.

### ISSUE THREAD

**Issue by imarban** [Nearsoft/questions#10]
PP Pending - must be Phase2 not later

Avoid hard coding the urls in freemarker views because when the mapping path for a controller method changes we have to remember to change though all the application.

**Comment by imarban** [comment]
Spring Taglib offers a mvcUrl, we can import spring taglib into freemarker views and create the urls.

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/MvcUriComponentsBuilder.html#fromMappingName-java.lang.String-

**Comment by imarban** [comment]
Freemarker does not find the TLD for taglibs in a Spring Boot application, by default it looks for TLD in WEB-INF directory, it does not exist in a Spring Boot App

**Comment by wdonet** [comment]
I was thinking in using groovy templates instead of freemarker

**Comment by imarban** [comment]
I am closing this issue due the recommendation about building a Single Page Application and move the templates to the front end side.
