### ISSUE TITLE
Questions mark should be automatically added

### ISSUE THREAD

**Issue by xiumeteo** [Nearsoft/questions#109]
Questions mark are being added by users, they should be added automagically

<img width="665" alt="screen shot 2016-06-30 at 12 53 50 pm" src="https://cloud.githubusercontent.com/assets/506672/16498510/d42957c2-3ec1-11e6-94d8-c5b23ad2aba1.png">

**Comment by wdonet** [comment]
This is not convenient from a UX point of view and it would complex the app in a point where at this moment we don't like to.
We won't do this feature :(
