### ISSUE TITLE
When trying to edit a question, submit button doesn't show.

### ISSUE THREAD

**Issue by vanchondo** [Nearsoft/questions#121]
When I'm trying to edit a question I click on the edit button then I change the question but no submit button is displayed to save changes.

<img width="1026" alt="screen shot 2016-07-25 at 12 56 20 pm" src="https://cloud.githubusercontent.com/assets/19497466/17146919/8fcfdcfc-531d-11e6-8422-12fe1ec4b564.png">
I click on the edit button.
And change the question.

<img width="1022" alt="screen shot 2016-07-25 at 12 56 46 pm" src="https://cloud.githubusercontent.com/assets/19497466/17146930/9cfbd82c-531d-11e6-9d50-028f9768afd4.png">

**Comment by wdonet** [comment]
any update? can we close it for now?

**Comment by wdonet** [comment]
Closing as not reproducible for now, please reopen if it happens again
