### ISSUE TITLE
/api/questions/suggestions

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#126]
This is to return suggestions to autocomplete questions on the UI while the user is writing.

To do:
 - [x] The API call should return up to 10 options (configurable through #125) for the user to select on the UI.
 - [x] JSON response as array:
`{
	"suggestions": [
		"suggestion1",
		"suggestion2"
	]
}`
 - [x] Update documentation

Notes:
 - While #125 is not done, the number of options could be hardcoded.
 - Developer can improve or change the response format, he just need to update documentation

**Comment by cesartg** [comment]
Solved. PR #144 merged.
