### ISSUE TITLE
Reputation count performance

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#127]
Thinking in the time when we had tons of questions with several answers each.  The way we store points earned by users is the best way?

If not
 - How can we improve performance ?
 - Is there something we can think of now in order to avoid a bad performance in one year?
 - Is it doable?

**Comment by jd-hernandez** [comment]
Currently we don't have to worry about performance on this feature, we should probably revisit this once we have users with tens of thousands of points.

**Comment by wdonet** [comment]
thanks @jd-hernandez , moving it to our backlog and un-assigning you
