### ISSUE TITLE
Fix style and icon for all existent notification types

### ISSUE THREAD

**Issue by iuresti** [Nearsoft/questions#134]
Fix in the list of notifications and in the inbox

**Comment by wdonet** [comment]
Is this half-fixed? saw new icons on inbox but not the popup, any update?

**Comment by iuresti** [comment]
Yes.. it is half-fixed. I fix inbox.ftl in order to avoid an exception for unmanaged notification types. Before complete this one I'll finish #131 .

What do you mean with the popup?

**Comment by iuresti** [comment]
@wdonet could you check please if any of style or icons for notifications need to be fixed? Most of them have been improved with other fixes

**Comment by wdonet** [comment]
I think we should get the icons back in the popup window when clicking on the notifications bell.

**Comment by iuresti** [comment]
Sure, working on that
