### ISSUE TITLE
Preguntas por usuario

### ISSUE THREAD

**Issue by LiliReina** [Nearsoft/questions#138]
Que en cada perfil se pueda ver las preguntas que hizo el usuario.

**Comment by wdonet** [comment]
Several goals for this issue when you go to http://www.nuuk.me/profile

 - [ ] Re-order current elements in a more suitable way as image shows
 - [ ] Keep the profile image rounded (style stuff)
 - [ ] Show my questions section in half page with link to the question
 - [ ] Show the questions where I provided an answer in the other half of page with link to the answer
![my profile](https://cloud.githubusercontent.com/assets/1031454/18015753/db4c0de0-6b7d-11e6-8cc1-c6084fc1ad91.png)
