### ISSUE TITLE
Improve Search Engine

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#139]
As a user, I should be able to find what I'm looking for easier.  Don't need to indicate only words but phrases and matches don't need to be exactly the same.

Searches should be looking at question title/description for now.  And we should be able to use phrases or group of words.

Think in :
- Getting Started ([video](https://www.elastic.co/webinars/get-started-with-elasticsearch?elektra=home&storm=banner&iesrc=ctr))
- The Definitive [Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html)
- Spring Data with [ElasticSearch](http://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/)

**Comment by wdonet** [comment]
Adding you Ramiro since you show interest on this topic.  Prepare yourself with links above.  Any suggestion is welcomed anytime. Thanks!

**Comment by wdonet** [comment]
I'm unassigned due to the bots task and will rely on you guys for this task to be completed, thanks !

**Comment by wdonet** [comment]
any update?

**Comment by jd-hernandez** [comment]
Closing this. As I'm going to do a full rewrite to fix bug #163.
