### ISSUE TITLE
Users shouldn't be able to vote more than once an item

### ISSUE THREAD

**Issue by iuresti** [Nearsoft/questions#151]
Currently users are available to vote any times to a question or answer. If user voted previously for an item, instead of arrows to vote again the user should see only a link to remove his/her own vote.

If user removes his/her own vote, then he/she be able to see again the arrows to vote the item.

**Acceptance Criteria**:
- User should vote once per question (1 up, 1 down are allowed, no more)
- When user clicks up/down vote button:
  - If user has not previously voted (button with white background and colored arrow/border):
    - In BE, a new vote is added
    - In FE, the button background is colored and arrow set white
  - If user has previously voted (button with colored background/border and white arrow):
    - In BE, the previous vote is removed
    - in FE, the button background is 'whited' and the arrow/border colored.
- Reputation shouldn't be affected due to adding/removing a single vote several times on the same question/answer

**Comment by iuresti** [comment]
- [ ] Add user to entities RuleAnswerTransaction and RuleQuestionTransaction in order to store the user generating each vote
- [ ] Create ad-hoc query in repository to get in a single step question, answers and a flag to indicate if user logged in has voted for each item
- [ ] Update view for one question in order to use the new query and object returned

**Comment by wdonet** [comment]
I added details in #180
