### ISSUE TITLE
Create an Admin to customize the app's features

### ISSUE THREAD

**Issue by wombstrat** [Nearsoft/questions#156]
Some of the app's features/properties must be customizable to fit client's needs.
- [x] Create and /adm page , where you could select and customize the app's properties.
- [x] The app logo will be customizable.
- [x] The index logo header will be customizable.
- [x] The index header's text will be customizable.
- [x] Change configurations 
  - [ ] Add configuration for selecting the initial page (home)

**Comment by wdonet** [comment]
Closing since all was already completed
