### ISSUE TITLE
When language is not set or is invalid english must be used.

### ISSUE THREAD

**Issue by iuresti** [Nearsoft/questions#170]
We are considering that the admin user will use a correct value for any configuration, but what if a wrong value is set and we don't have that value as valid in our system?  For instance, the language.

If the admin user introduces an invalid language (let's say it's invalid because it doesn't exist in our DB and we don't have translations for it), we'll cause a NPE (Null Pointer Exception) when TranslationServiceImpl # getAllTranslationsByCode() method is called :

`translationRepository.findByCode(code).**forEach**`

Acceptance Criteria:
If the config contains an invalid language, the UI should show translations in English as default.

**Comment by ragore09** [comment]
@iuresti An extra validation was added to avoid nulls or not valid languages.

**Comment by wdonet** [comment]
closing since it was already merged
