### ISSUE TITLE
Optimize I18N

### ISSUE THREAD

**Issue by iuresti** [Nearsoft/questions#171]
Currently each time any page of Nuuk is loaded it is executed a query to get all the entries of translations for the configured language and it is created a map to store the translations retrieved.

It is necessary to optimize the use of memory such as avoid to execute the query every time a page is loaded.

As a suggestion the table can be managed by a singleton object (managed by spring)

**Comment by ragore09** [comment]
this issue has been worked and merged in devQuestions and hackDay
