### ISSUE TITLE
Upvote or downvote questions multiple times

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#180]
_Upvoting or downvoting multiple times shouldn't be allowed for questions and answers._

**Acceptance Criteria**:
- User should vote once per question (1 up, 1 down are allowed, no more)
- When user clicks up/down vote button:
  - If user has not previously voted (button with white background and colored arrow/border):
    - In BE, a new vote is added
    - In FE, the button background is colored and arrow set white
  - If user has previously voted (button with colored background/border and white arrow):
    - In BE, the previous vote is removed
    - in FE, the button background is 'whited' and the arrow/border colored.
- Reputation shouldn't be affected due to adding/removing a single vote several times on the same question/answer

**Comment by wdonet** [comment]
closing in favor of #151

**Comment by iuresti** [comment]
@wdonet Is a user allowed to vote up and down the same question?

**Comment by iuresti** [comment]
@wdonet with the rule:

Reputation shouldn't be affected due to adding/removing a single vote several times on the same question/answer 

you mean... when the user vote a question he/she receives the points for that action, when the user removes his/her vote those points are also removed from his/her reputation?

**Comment by wdonet** [comment]
> @wdonet Is a user allowed to vote up and down the same question?
R : I'd say no, one or the other

> you mean... when the user vote a question the owner receives the points for that action, when a user removes his/her vote those points are also removed from the owner's reputation?

I think this ^ is the best approach
