### ISSUE TITLE
Translation Editor

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#182]
As Admin User I would like to edit translations as I do with configurations .

**Acceptance Criteria**
 - Add new admin section for changing translations
 - There should be:
   - Text box to search by key (part of it)
   - Text box to search by value (part of it)
   - Results should show a list of key with a text box and the corresponding value
   - The value, if changed, should be updated individually without affecting other results in the list

**Comment by ragore09** [comment]
added [commit](https://github.com/Nearsoft/questions/commit/aab97158bf9ceeeef4bc999caa170c02dfd37ccf) with translation tab for admin menu

**Comment by wdonet** [comment]
closing since it was already merged
