### ISSUE TITLE
footer not showing for initial page

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#206]
In admin page User is able to customize header, content, footer and styles for initial page.
![image](https://cloud.githubusercontent.com/assets/1031454/21114332/910b8c54-c061-11e6-9dce-28b42f91cba2.png)

However, when adding something in **Footer** is not showing anything of that at the initial page.
It seems it exists when searching the text but it's not visible

**Comment by ragore09** [comment]
@wdonet I wrote a value in the footer section and I can see it in the home page, as shown in the images attached.
Can you tell me what value are you trying to save in the admin page?

![screen shot 2016-12-12 at 15 18 18](https://cloud.githubusercontent.com/assets/8495722/21117204/54a3c570-c07e-11e6-9add-e14418393132.png)
![screen shot 2016-12-12 at 15 18 38](https://cloud.githubusercontent.com/assets/8495722/21117210/59062f4a-c07e-11e6-8970-5453941ebe79.png)

**Comment by wdonet** [comment]
This was MTS
