### ISSUE TITLE
For "!" right-hand operand: Expected a boolean, but this has evaluated to an extended_hash+string 

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#208]
When showing 1 question with answers it's throwing an error because of the FTL.

It seems we use a wrong evaluation of the conditional as:
`!answer.status == 'OBSOLETE'`
and should be
`answer.status != 'OBSOLETE'`

First part of the stacktrace:

> For "!" right-hand operand: Expected a boolean, but this has evaluated to an extended_hash+string (com.nearsoft.questions.domain.ItemStatus wrapped into f.e.b.StringModel): ==> answer.status [in template "showOneQuestion.ftl" at line 157, column 111] ---- FTL stack trace ("~" means nesting-related): - Failed at: #assign canVoteUpAnswer = !ownsAnswer... [in template "showOneQuestion.ftl" at line 157, column 17] ---- Java stack trace (for programmers): ---- freemarker.core.NonBooleanException: [... Exception message was already printed; see it above ...] 

Steps to reproduce:
- Go to http://dev.nuuk.me/question/11 and the error will display

Related to #193 Obsolete answers

**Comment by ldurazo** [comment]
Fixed
