### ISSUE TITLE
Add unit tests for the following methods

### ISSUE THREAD

**Issue by luisalduucin** [Nearsoft/questions#212]
**Add unit tests for the following methods:**

- [x] `ConfigurationServiceImpl#getInteger()`
- [x] `ConfigurationServiceImpl#getDouble()`
- [x] `AnswerServiceImpl#markAsAccepted()`
- [x] `RuleServiceImpl#getUserPermissions()`
- [x] `ConfigurationServiceImpl#getInteger()`
- [x] `TagsSubscriptionServiceImpl#getAllTagsWithSubscriptionFlagSortedByName()`
- [x] `TranslationServiceImpl#getAllTranslationsByCode()`
- [x] `VotesByAnswerServiceImpl#onVotedUp()`
- [x] `VotesByAnswerServiceImpl#onVotedDown()`
- [x] `VotesByAnswerServiceImpl#removePreviousVote()`
- [x] `VotesByQuestionServiceImpl#onVotedUp()`
- [x] `VotesByQuestionServiceImpl#onVotedDown()`
- [x] `VotesByQuestionServiceImpl#removePreviousVote()`

**Comment by wdonet** [comment]
This was MTS
