### ISSUE TITLE
FTL migration -> React JS

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#27]
Time: 24h
Goal:
1. React configuration and deal with Heroku settings
2. Migrate 10  FTL's to React JS listed in: https://github.com/Nearsoft/questions/tree/master/src/main/resources/templates (10 FTL's)
3. Definition of the json RQ & RS

**Comment by imarban** [comment]
We have the first initial migration on[feature/frontend](https://github.com/Nearsoft/questions/tree/feature/frontend) branch
