### ISSUE TITLE
Accesing JPA Data with REST

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#3]
Time: 18 hrs
Goal:
1. Read and evaluate if accessing data via REST is what we need
 - Is it useful to make our repositories accesible via REST ?
 - Is it secured?
2. Make basic controllers configuration
3. Create controller for our current needs (10 FTLs)

Reference:
https://spring.io/guides/gs/accessing-data-rest/

**Comment by imarban** [comment]
After reading the Reference Guide I think that Spring Data REST is a good option for avoiding boilerplate code, we could use it to expose the data from the entities (Question, Answer, Users)

Yes, it is secured, you can add PreAuthorize or Secured annotations to a Repository or to specific methods in the class. http://docs.spring.io/spring-data/rest/docs/2.4.2.RELEASE/reference/html/#security

We'll need to write specific controllers for specific actions (voting, uploading an image, etc)

**Comment by wdonet** [comment]
so cool! , go ahead :+1:

**Comment by imarban** [comment]
![screen shot 2016-01-11 at 5 04 32 pm](https://cloud.githubusercontent.com/assets/2502032/12249437/66ccc67c-b885-11e5-87a2-49c0b0972c6e.png)

Spring JPA Rest generates links for embedded objects, as the properties within entity classes start with underscore, then they look weird in urls. What is supposed to do? :sos:

**Comment by wdonet** [comment]
I was planning in a rework to correct that eliminating underscores and for id columns.  It would be great having hands on there.

**Comment by imarban** [comment]
I've created #29 to fix this

**Comment by imarban** [comment]
Closing this as #29 solved the name problem for properties.
We can see how spring data rest works in https://github.com/Nearsoft/questions/tree/feature/api
