### ISSUE TITLE
Create search endpoint and document it

### ISSUE THREAD

**Issue by imarban** [Nearsoft/questions#39]
Create the endpoint for exposing the search functionality. This functionality is working now, we just need to expose it.

The endpoint must support the following parameters:

1.  Page. For indicating which page of results is required.
2.  Size. To indicate how many results are required per page. 

We need to add a unit test for this.

**Comment by imarban** [comment]
The questions search endpoint has been created in 1588ac2. It works like any other api endpoint. Use sort, page and size as parameters to control it.

**Comment by imarban** [comment]
I forgot to mention. The url for this endpoint is the following /api/questions/search?term=<query>

**Comment by wdonet** [comment]
| URI | Description | Pagination | Sorting | + Params |
|:--- |:----------- |:----------:|:-------:|:------------ |
| GET `/api/questions/search` | Search questions using ?term={term} param| Yes | Yes | `term` |
