### ISSUE TITLE
Add Continuous Integration tool to the project.

### ISSUE THREAD

**Issue by imarban** [Nearsoft/questions#41]
We need to add and configure a Continuous Integration tool. If we could look for an option with Github/Heroku integration that would be awesome, in that way we can see the current status for the project in our repository and wait for the test passing for deploying in Heroku.

**Comment by wdonet** [comment]
We should have a few options on the github or heroku accounts that NS is paying.  Maybe you can follow up with @abadongutierrez for the heroku account, he's now the owner of the repository for the project and he's in charge of giving us those kind of privilegies

**Comment by wdonet** [comment]
any update on this? cc @cesartg

**Comment by wdonet** [comment]
Seems it is done at:

- Travis : https://travis-ci.org/Nearsoft/questions/
- Codeship : https://codeship.com/projects/151404

Closing for now but we should decide which is the best for the project
cc @imarban
