### ISSUE TITLE
UX Improvements - phase 1

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#44]
Creation of wireframes to follow new UI improvements and bugs (structure only)

Estimate Time: 14 hrs

**Comment by mmedina-nearsoft** [comment]
![searchformhome](https://cloud.githubusercontent.com/assets/7750508/15163299/8a0dc5c4-16bc-11e6-906d-5d5974f3b3ff.png)
![noresults](https://cloud.githubusercontent.com/assets/7750508/15163300/8a10492a-16bc-11e6-803f-39492e0bdaf7.png)
![answer](https://cloud.githubusercontent.com/assets/7750508/15163302/8a12df0a-16bc-11e6-898d-d0aabf815512.png)
![seequestions](https://cloud.githubusercontent.com/assets/7750508/15163303/8a130c28-16bc-11e6-9e4d-652f887a5d05.png)
![home](https://cloud.githubusercontent.com/assets/7750508/15163301/8a12d622-16bc-11e6-8d29-3898c93b5a14.png)

**Comment by wdonet** [comment]
Closing since it is related to #51 to follow up with phase 2
