### ISSUE TITLE
Make links on the answers actual links

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#49]
Use one tools to render content as HTML, Consider:
- HTML introduction in web form
- Validation in front end
- Validation in back end
- DB adjustments ?

Estimate Time: 10 hrs

**Comment by imarban** [comment]
Consider to use BBCode editor, save BB code into the database and render it in safe way.

**Comment by wdonet** [comment]
Leave it with generation of links only .  I'm more confident in using a **markdown** editor than those _WYSIWYG_. what do you think @eduarbo @imarban ?

Look at this [comparison](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md) and look at [alloyeditor](http://alloyeditor.com/demo/) (looks promising and was built with react.  It's heavy though)

I also like stackoverflow editor, same as github editor

**Comment by imarban** [comment]
I haven't thought about a markdown editor but I think it's a better option than a bbcode

**Comment by wdonet** [comment]
Kept exploring and found:

1. [showdown](https://github.com/showdownjs/showdown)
2. chjj [marked](https://github.com/chjj/marked)

Tried with last one - take a look to the form when adding a question, it has a preview div and saves the content as the source, we could use the same for rendering question/answer descriptions
@imarban @eduarbo

**Comment by wdonet** [comment]
Tried with Showdown, it is more configurable.  Result is almost the same between the two.  Check it out @eduarbo @imarban !  Need to change implementation in lines 9-10 of askQuestion.js

**Comment by imarban** [comment]
I thought you were talking about a WYSIWYG editor but using Markdown instead of BBCode. I found this one and I think it deserves a try. https://simplemde.com/

**Comment by wdonet** [comment]
you're right @imarban - Just committed the change using SimpleMDE and seems to work better with a similar toolbar on textarea like in github, very similar. You can use shortcuts and previews in full screen too.  It's really nice.  I'll keep this one.

Had to adjust with some styling though.

Reopenining since it's not totally done.  Rendering for question/answer description is missing yet.
