### ISSUE TITLE
Notification System (UI View)

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#61]
As a user I would like to communicate changes to other's about posts made (questions/answers).

- [x] I should be able to see an inbox link at the top
- [x] Clicking on the top link a list of notifications should be displayed in a new page
- [x] Each notification in the list is a short description for the change involved
- [x] Clicking on each notification I should be redirected to the original post (i.e. question)

- A notification could be generated by:
   - #63 Question closed due to improvement (moved to the backlog)
   - #64 Notification for Question improved (moved to the backlog)
   - [x] #65 Any time a question is added for the tags I am subscribed to
   - [x] #66 Any modification of points by the rules executed
   - [x] A new answer was added to my question

**Comment by mmedina-nearsoft** [comment]
![notification-page](https://cloud.githubusercontent.com/assets/7750508/15376848/855c8816-1d0c-11e6-8fa9-9a38f0c82436.png)
![notifications](https://cloud.githubusercontent.com/assets/7750508/15376849/855e05d8-1d0c-11e6-8c08-e0188a621f85.jpg)
