### ISSUE TITLE
Leave comments on questions

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#72]
As a user I would like use comments to ask for more information or clarify a question.

I could always comment on my own questions.
or
Once I earn the reputation level (#57) , I can comment on anybody's post.

**Comment by vanchondo** [comment]
A table named question_comments will be created to store question's comments.
Table structure:
question_comments: {
  id: long,
  description: string,
  question_id: long,
  user_id: int,
  created_at: date,
  updated_at: date
}

**Comment by wdonet** [comment]
Leaving reputation thing for comments on the side.  It doesn't make sense for now.  Closing for now
