### ISSUE TITLE
Leave comments on answers

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#73]
As a user I would like use comments to ask for more information or clarify a answer.

I could always comment on my own answers.
or
Once I earn the reputation level (#57) , I can comment on anybody's post.

**Comment by vanchondo** [comment]
A table named answer_comments will be created to store answer's comments.
Table structure:
answer_comments: {
  id: long,
  description: string,
  answer_id: long,
  user_id: int,
  created_at: date,
  updated_at: date
}

**Comment by wdonet** [comment]
Leaving reputation thing for comments on the side.  It doesn't make sense for now.  Closing for now
