### ISSUE TITLE
Clock icon is too close to the date.

### ISSUE THREAD

**Issue by gsancheznearsoft** [Nearsoft/questions#90]
Currently, the clock icon from comments is too close to the date, which could cause overlap.

Screenshot below:

![image](https://cloud.githubusercontent.com/assets/2767847/15720108/9e00a96e-27f8-11e6-99ef-69fc7fb0d94e.png)

**Comment by vanchondo** [comment]
This is done. 
<img width="123" alt="screen shot 2016-06-01 at 1 02 03 pm" src="https://cloud.githubusercontent.com/assets/19497466/15720241/232b851e-27f9-11e6-9bf5-334c24fb4554.png">
