### ISSUE TITLE
delete reputation branch

### ISSUE THREAD

**Issue by wdonet** [Nearsoft/questions#98]
Verify all commits of [bill branch](https://github.com/Nearsoft/questions/tree/bill) are on [hackday branch](https://github.com/Nearsoft/questions/tree/hackday) so that we can delete **bill branch**.

**Comment by laguilarNearsoft** [comment]
All commits of bill branch are on hackday branch

**Comment by wdonet** [comment]
perfect ! agree with deletion , thanks. Once it's done, pls close this issue.  Thanks
